# Generated by Django 2.0.2 on 2018-03-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # migrations.RenameModel('Cellphones', 'Cellphone')
        # #migrations.RenameModel('Devices', 'Device')
        # migrations.RenameModel('Scams', 'Scam')
        # migrations.RenameModel('PCs', 'PC')
        # migrations.RenameModel('Tablets', 'Tablet')
        # migrations.RenameModel('Laptops', 'Laptop')
        # migrations.RenameModel('Departments', 'Department')
        # migrations.RenameModel('BinaryEntries', 'BinaryEntry')
        # migrations.RenameModel('Entries', 'Entry')
        # migrations.RenameModel('Cities', 'City')
    ]
