# Generated by Django 2.0.2 on 2018-04-03 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BinaryEntry',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('household_size', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recurrence',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('recurrence', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ScamType',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TrustLevel',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cellphone',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('quantity', models.IntegerField()),
                ('home', models.ForeignKey(db_column='home', on_delete=django.db.models.deletion.PROTECT, related_name='cellphone_home', to='webapp.BinaryEntry')),
                ('utilize', models.ForeignKey(db_column='utilize', on_delete=django.db.models.deletion.PROTECT, related_name='cellphone_use', to='webapp.BinaryEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('quantity', models.IntegerField()),
                ('home', models.ForeignKey(db_column='home', on_delete=django.db.models.deletion.PROTECT, related_name='laptop_home', to='webapp.BinaryEntry')),
                ('utilize', models.ForeignKey(db_column='utilize', on_delete=django.db.models.deletion.PROTECT, related_name='laptop_use', to='webapp.BinaryEntry')),
            ],
        ),
        migrations.CreateModel(
            name='LaptopRecurrence',
            fields=[
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Recurrence')),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('quantity', models.IntegerField()),
                ('home', models.ForeignKey(db_column='home', on_delete=django.db.models.deletion.PROTECT, related_name='pc_home', to='webapp.BinaryEntry')),
                ('utilize', models.ForeignKey(db_column='utilize', on_delete=django.db.models.deletion.PROTECT, related_name='pc_use', to='webapp.BinaryEntry')),
            ],
        ),
        migrations.CreateModel(
            name='PCRecurrence',
            fields=[
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Recurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Scam',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('reported', models.ForeignKey(db_column='reported', on_delete=django.db.models.deletion.PROTECT, to='webapp.BinaryEntry')),
                ('scam_type', models.ForeignKey(db_column='scam_type', on_delete=django.db.models.deletion.PROTECT, to='webapp.ScamType')),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('quantity', models.IntegerField()),
                ('home', models.ForeignKey(db_column='home', on_delete=django.db.models.deletion.PROTECT, related_name='smartphone_home', to='webapp.BinaryEntry')),
                ('utilize', models.ForeignKey(db_column='utilize', on_delete=django.db.models.deletion.PROTECT, related_name='smartphone_use', to='webapp.BinaryEntry')),
            ],
        ),
        migrations.CreateModel(
            name='SmartphoneRecurrence',
            fields=[
                ('entry_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Recurrence')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('entry_id', models.OneToOneField(db_column='entry_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='webapp.Entry')),
                ('quantity', models.IntegerField()),
                ('home', models.ForeignKey(db_column='home', on_delete=django.db.models.deletion.PROTECT, related_name='tablet_home', to='webapp.BinaryEntry')),
                ('utilize', models.ForeignKey(db_column='utilize', on_delete=django.db.models.deletion.PROTECT, related_name='tablet_use', to='webapp.BinaryEntry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.City'),
        ),
        migrations.AddField(
            model_name='entry',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Gender'),
        ),
        migrations.AddField(
            model_name='entry',
            name='internet_trust',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.TrustLevel'),
        ),
        migrations.AddField(
            model_name='entry',
            name='news_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.NewsSource'),
        ),
        migrations.AddField(
            model_name='entry',
            name='preferred_device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Device'),
        ),
        migrations.AddField(
            model_name='entry',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.SocialMedia'),
        ),
        migrations.AddField(
            model_name='city',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Department'),
        ),
    ]
